feat: 영화 평점이 8점이상일 경우 hot icon 제목옆에 표시
jsontype/generalapp pull request #21
Opened 2023-02-04 11:51 UTC by joonyub

#### 개요
영화 평점이 8점이상일 경우 hot icon 제목옆에 표시

#### 테스트
평점 8 이상 영화 표시를 위해 sort_by=rating 주석해제 후 확인

2023-02-04 11:52 UTC, joonyub commented
@jsontype #18

2023-02-06 04:42 UTC, jsontype requested changes
이하 대응 부탁드려요

2023-02-06 04:42 UTC, jsontype commented on src/components/Movies/index.js
> +            {item.title} {item.rating <= 7 ? '' : '🔥'} ({item.year})
반대로 해주시겠어요? {item.rating >= 8 ? '🔥' : ''}

2023-02-10 12:46 UTC, joonyub commented on src/components/Movies/index.js
> +            {item.title} {item.rating <= 7 ? '' : '🔥'} ({item.year})
対応しました。

2023-02-10 12:57 UTC, joonyub commented
対応しました。

2023-02-11 06:04 UTC, merged